spring:
  datasource:
    #    url: jdbc:h2:mem:testdb
    url: jdbc:h2:~/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true # localhost:8080/h2-console
  jpa:
#    open-in-view: true
#    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#        hbm2ddl:
#          auto: <- ?? ddl-auto? ??? ???? properties ? ?? ???? ?? ???? ?? ????? ???