spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

uploadPath: /asdf