springdoc.swagger-ui.path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:h2:mem:testdb # memory mode
#    url: jdbc:h2:~/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true # localhost:8080/h2-console
  jpa:
#    open-in-view: true
#    generate-ddl: true
    show-sql: true
    open-in-view: false # false 일 경우 JPA transaction 이 commit 된 후, JPA EntityManager 가 닫혀 더 이상은 지연로딩을 할 수 없다.
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true # show sql true 일 때 formatting
        show_sql: true
        use_sql_comment: true # 쿼리에 추가적인 주석을 표시할지 설정하는 옵션
        highlight_sql: true
#        hbm2ddl:
#          auto: <- ?? ddl-auto? ??? ???? properties ? ?? ???? ?? ???? ?? ????? ???

# ? 파라미터 바인딩
#logging:
#  level.org.hibernate:
#    SQL: DEBUG
#    orm.jdbc.bind: TRACE

# logging.level.org.hibernate.type=TRACE,
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# 이 옵션들은 부트 3에서 안되는듯?

