server:
  #  port: 9001
  port: 0 # 0? ?? ?? ?? ?? - eureka ??? ? ?? ????? ??? ???? ????? 0?? ?? ??. ??? instance id? ?? ???? ??.

spring:
  application:
    name: sample-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true # eureka ??? ??? ??? ??
    fetch-registry: true # ? ?????? ?? ???? endpoints? ?? ??? ?????? ?? Eureka ??? ??? ???? ???, ???? ???? ????? ??? ???? ?? ??
    service-url:
      default-zone: http://localhost:8761/eureka
