spring:
  application.name: mock-socket-server
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 생성
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true  # H2 웹 콘솔 활성화
      path: /h2-console  # H2 콘솔 경로 설정