version: '3.8'

services:
  tc-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elk-pipeline-elasticsearch
    environment:
      - node.name=single
      - discovery.seed_hosts=es
      - cluster.name=standalone
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

  tc-kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: elk-pipeline-kibana
    environment:
      ELASTICSEARCH_HOSTS: '["http://tc-es:9200"]'
    ports:
      - 5601:5601
    expose:
      - 5601
    restart: no
    depends_on:
      - tc-es

  tc-logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: elk-pipeline-logstash
    environment:
#      - xpack.monitoring.enabled=false
#      - xpack.monitoring.elasticsearch.hosts=["http://tc-es:9200"]
      - path.data=/usr/share/logstash/data
    volumes:
      - ./data/logstash/config:/usr/share/logstash/config
      - ./data/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5044:5044
      - 9600:9600
    depends_on:
      - tc-es