spring:
  datasource:
    url: jdbc:mysql://localhost:3306:testdb
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
