server:
  port: 0

spring:
  application:
    name: category-service

  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true # eureka ??? ??? ??? ??
    fetch-registry: true # ? ?????? ?? ???? endpoints? ?? ??? ?????? ?? Eureka ??? ??? ???? ???, ???? ???? ????? ??? ???? ?? ??
    service-url:
      default-zone: http://localhost:8761/eureka
