version: '3.8'
services:
  tc-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es-singlenode
    environment:
      - node.name=single
      - discovery.seed_hosts=es
      - cluster.name=standalone
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    # networks:
    #   - es-bridge

  tc-kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      # - ELASTICSEARCH_HOSTS=http://es:9200
      ELASTICSEARCH_HOSTS: '["http://host.docker.internal:9200"]'
    ports:
      - 5601:5601
    expose:
      - 5601
#    volumes:
#      - ./kibana-config.yml:/usr/share/kibana/config/kibana.yml
    restart: always
    depends_on:
      - tc-es

#     network_mode: es-bridge

# networks:
#   es-bridge:
#     driver: bridge

