version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-batch-container
    restart: always
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: BATCH_TEST
      MYSQL_ROOT_PASSWORD: 1234
