spring:
  profiles:
    active: local

  datasource:
    #    url: jdbc:h2:tcp://localhost/~/test
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

      properties:
        hibernate:
          show_sql: true
          format_sql: true
  h2:
    console:
      enabled: true
