spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
#    generate-ddl: true
    hibernate:
      ddl-auto: update