spring:
  application:
    name: product-service

  kafka:
    bootstrap-servers: localhost:9092

# actuator 설정
# actuator는 서비스의 런타임 정보와 서비스의 운영 상태 정보를 제공한다.
management:
  endpoints:
    web:
      base-path: / # http://localhost:8080/health
      exposure:
        include: refresh,health,beans,busrefresh,httptrace
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: false
    diskspace:
      enabled: true
