server:
#  port: 0 # 0일 경우 사용하지 않는 포트 아무거나 배정되나 현재 application.yml에서 ${server.port}로 값을 불러오면 0이 나오는 문제점이 있다
  port: ${random.int(50000,51000)} # 범위 값 안의 랜덤 값이 설정 된다.

spring:
  application:
    name: product-service

  kafka:
    bootstrap-servers: localhost:9092

# actuator 설정
# actuator는 서비스의 런타임 정보와 서비스의 운영 상태 정보를 제공한다.
management:
  endpoints:
    web:
      base-path: / # http://localhost:8080/health
      exposure:
        include: refresh,health,beans,busrefresh,httptrace
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: false
    diskspace:
      enabled: true

eureka:
  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    instance-id: ${spring.cloud.client.hostname}:${server.port} # 0이 아닌 실제 포트 번호를 랜덤으로 정해줬으므로 port로 표시 가능
  client:
    register-with-eureka: true # eureka 서버에 등록할 것인지 유무
    fetch-registry: true # 이 클라이언트가 다른 서비스의 endpoints에 대한 정보를 다운로드하기 위해 Eureka 서버에 연결을 시도할지 여부로, 유레카에 등록되는 서비스들의 정보를 갱신하기 위한 용도
    service-url:
      default-zone: http://localhost:8761/eureka
